//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.Facade.BotService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BotService.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebService.Facade.BotService.HelloWorldResponse HelloWorld(WebService.Facade.BotService.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 JsonLuisResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetResult", ReplyAction="*")]
        WebService.Facade.BotService.GetResultResponse GetResult(WebService.Facade.BotService.GetResultRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 JsonLuisResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFuzzyResult", ReplyAction="*")]
        WebService.Facade.BotService.GetFuzzyResultResponse GetFuzzyResult(WebService.Facade.BotService.GetFuzzyResultRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 JsonLuisResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetActionResult", ReplyAction="*")]
        WebService.Facade.BotService.GetActionResultResponse GetActionResult(WebService.Facade.BotService.GetActionResultRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 actionId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBooksList", ReplyAction="*")]
        WebService.Facade.BotService.GetBooksListResponse GetBooksList(WebService.Facade.BotService.GetBooksListRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetDefaultResultResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDefaultResult", ReplyAction="*")]
        WebService.Facade.BotService.GetDefaultResultResponse GetDefaultResult(WebService.Facade.BotService.GetDefaultResultRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebService.Facade.BotService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebService.Facade.BotService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebService.Facade.BotService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebService.Facade.BotService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResult", Namespace="http://tempuri.org/", Order=0)]
        public WebService.Facade.BotService.GetResultRequestBody Body;
        
        public GetResultRequest() {
        }
        
        public GetResultRequest(WebService.Facade.BotService.GetResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string JsonLuisResult;
        
        public GetResultRequestBody() {
        }
        
        public GetResultRequestBody(string JsonLuisResult) {
            this.JsonLuisResult = JsonLuisResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResultResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebService.Facade.BotService.GetResultResponseBody Body;
        
        public GetResultResponse() {
        }
        
        public GetResultResponse(WebService.Facade.BotService.GetResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetResultResult;
        
        public GetResultResponseBody() {
        }
        
        public GetResultResponseBody(string GetResultResult) {
            this.GetResultResult = GetResultResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFuzzyResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFuzzyResult", Namespace="http://tempuri.org/", Order=0)]
        public WebService.Facade.BotService.GetFuzzyResultRequestBody Body;
        
        public GetFuzzyResultRequest() {
        }
        
        public GetFuzzyResultRequest(WebService.Facade.BotService.GetFuzzyResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFuzzyResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string JsonLuisResult;
        
        public GetFuzzyResultRequestBody() {
        }
        
        public GetFuzzyResultRequestBody(string JsonLuisResult) {
            this.JsonLuisResult = JsonLuisResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFuzzyResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFuzzyResultResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebService.Facade.BotService.GetFuzzyResultResponseBody Body;
        
        public GetFuzzyResultResponse() {
        }
        
        public GetFuzzyResultResponse(WebService.Facade.BotService.GetFuzzyResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFuzzyResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetFuzzyResultResult;
        
        public GetFuzzyResultResponseBody() {
        }
        
        public GetFuzzyResultResponseBody(string GetFuzzyResultResult) {
            this.GetFuzzyResultResult = GetFuzzyResultResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActionResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActionResult", Namespace="http://tempuri.org/", Order=0)]
        public WebService.Facade.BotService.GetActionResultRequestBody Body;
        
        public GetActionResultRequest() {
        }
        
        public GetActionResultRequest(WebService.Facade.BotService.GetActionResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetActionResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string JsonLuisResult;
        
        public GetActionResultRequestBody() {
        }
        
        public GetActionResultRequestBody(string JsonLuisResult) {
            this.JsonLuisResult = JsonLuisResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActionResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActionResultResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebService.Facade.BotService.GetActionResultResponseBody Body;
        
        public GetActionResultResponse() {
        }
        
        public GetActionResultResponse(WebService.Facade.BotService.GetActionResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetActionResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetActionResultResult;
        
        public GetActionResultResponseBody() {
        }
        
        public GetActionResultResponseBody(string GetActionResultResult) {
            this.GetActionResultResult = GetActionResultResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBooksListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBooksList", Namespace="http://tempuri.org/", Order=0)]
        public WebService.Facade.BotService.GetBooksListRequestBody Body;
        
        public GetBooksListRequest() {
        }
        
        public GetBooksListRequest(WebService.Facade.BotService.GetBooksListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBooksListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string actionId;
        
        public GetBooksListRequestBody() {
        }
        
        public GetBooksListRequestBody(string actionId) {
            this.actionId = actionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBooksListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBooksListResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebService.Facade.BotService.GetBooksListResponseBody Body;
        
        public GetBooksListResponse() {
        }
        
        public GetBooksListResponse(WebService.Facade.BotService.GetBooksListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBooksListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBooksListResult;
        
        public GetBooksListResponseBody() {
        }
        
        public GetBooksListResponseBody(string GetBooksListResult) {
            this.GetBooksListResult = GetBooksListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDefaultResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDefaultResult", Namespace="http://tempuri.org/", Order=0)]
        public WebService.Facade.BotService.GetDefaultResultRequestBody Body;
        
        public GetDefaultResultRequest() {
        }
        
        public GetDefaultResultRequest(WebService.Facade.BotService.GetDefaultResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDefaultResultRequestBody {
        
        public GetDefaultResultRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDefaultResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDefaultResultResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebService.Facade.BotService.GetDefaultResultResponseBody Body;
        
        public GetDefaultResultResponse() {
        }
        
        public GetDefaultResultResponse(WebService.Facade.BotService.GetDefaultResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDefaultResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDefaultResultResult;
        
        public GetDefaultResultResponseBody() {
        }
        
        public GetDefaultResultResponseBody(string GetDefaultResultResult) {
            this.GetDefaultResultResult = GetDefaultResultResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebService.Facade.BotService.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebService.Facade.BotService.WebService1Soap>, WebService.Facade.BotService.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.Facade.BotService.HelloWorldResponse WebService.Facade.BotService.WebService1Soap.HelloWorld(WebService.Facade.BotService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebService.Facade.BotService.HelloWorldRequest inValue = new WebService.Facade.BotService.HelloWorldRequest();
            inValue.Body = new WebService.Facade.BotService.HelloWorldRequestBody();
            WebService.Facade.BotService.HelloWorldResponse retVal = ((WebService.Facade.BotService.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.Facade.BotService.GetResultResponse WebService.Facade.BotService.WebService1Soap.GetResult(WebService.Facade.BotService.GetResultRequest request) {
            return base.Channel.GetResult(request);
        }
        
        public string GetResult(string JsonLuisResult) {
            WebService.Facade.BotService.GetResultRequest inValue = new WebService.Facade.BotService.GetResultRequest();
            inValue.Body = new WebService.Facade.BotService.GetResultRequestBody();
            inValue.Body.JsonLuisResult = JsonLuisResult;
            WebService.Facade.BotService.GetResultResponse retVal = ((WebService.Facade.BotService.WebService1Soap)(this)).GetResult(inValue);
            return retVal.Body.GetResultResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.Facade.BotService.GetFuzzyResultResponse WebService.Facade.BotService.WebService1Soap.GetFuzzyResult(WebService.Facade.BotService.GetFuzzyResultRequest request) {
            return base.Channel.GetFuzzyResult(request);
        }
        
        public string GetFuzzyResult(string JsonLuisResult) {
            WebService.Facade.BotService.GetFuzzyResultRequest inValue = new WebService.Facade.BotService.GetFuzzyResultRequest();
            inValue.Body = new WebService.Facade.BotService.GetFuzzyResultRequestBody();
            inValue.Body.JsonLuisResult = JsonLuisResult;
            WebService.Facade.BotService.GetFuzzyResultResponse retVal = ((WebService.Facade.BotService.WebService1Soap)(this)).GetFuzzyResult(inValue);
            return retVal.Body.GetFuzzyResultResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.Facade.BotService.GetActionResultResponse WebService.Facade.BotService.WebService1Soap.GetActionResult(WebService.Facade.BotService.GetActionResultRequest request) {
            return base.Channel.GetActionResult(request);
        }
        
        public string GetActionResult(string JsonLuisResult) {
            WebService.Facade.BotService.GetActionResultRequest inValue = new WebService.Facade.BotService.GetActionResultRequest();
            inValue.Body = new WebService.Facade.BotService.GetActionResultRequestBody();
            inValue.Body.JsonLuisResult = JsonLuisResult;
            WebService.Facade.BotService.GetActionResultResponse retVal = ((WebService.Facade.BotService.WebService1Soap)(this)).GetActionResult(inValue);
            return retVal.Body.GetActionResultResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.Facade.BotService.GetBooksListResponse WebService.Facade.BotService.WebService1Soap.GetBooksList(WebService.Facade.BotService.GetBooksListRequest request) {
            return base.Channel.GetBooksList(request);
        }
        
        public string GetBooksList(string actionId) {
            WebService.Facade.BotService.GetBooksListRequest inValue = new WebService.Facade.BotService.GetBooksListRequest();
            inValue.Body = new WebService.Facade.BotService.GetBooksListRequestBody();
            inValue.Body.actionId = actionId;
            WebService.Facade.BotService.GetBooksListResponse retVal = ((WebService.Facade.BotService.WebService1Soap)(this)).GetBooksList(inValue);
            return retVal.Body.GetBooksListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.Facade.BotService.GetDefaultResultResponse WebService.Facade.BotService.WebService1Soap.GetDefaultResult(WebService.Facade.BotService.GetDefaultResultRequest request) {
            return base.Channel.GetDefaultResult(request);
        }
        
        public string GetDefaultResult() {
            WebService.Facade.BotService.GetDefaultResultRequest inValue = new WebService.Facade.BotService.GetDefaultResultRequest();
            inValue.Body = new WebService.Facade.BotService.GetDefaultResultRequestBody();
            WebService.Facade.BotService.GetDefaultResultResponse retVal = ((WebService.Facade.BotService.WebService1Soap)(this)).GetDefaultResult(inValue);
            return retVal.Body.GetDefaultResultResult;
        }
    }
}
